### ISSUE TITLE
zer0m0n driver is not included in the repository

### ISSUE THREAD

**Issue by wbenny** [brad-accuvant/cuckoo-modified#106]
Any reason for not including it here? :)

**Comment by brad-sp** [comment]
I had planned to include it once I got around to modifying it to improve it a bit, which would involve providing the source instead of just the binaries, but I've run into too many other things that need improving in the meantime.  I'll accept a PR that adds a msvc project for zer0m0n to build with the DDK (it exists already on github) but it should be in its own repo similar to cuckoomon with updates to the associated binaries once the changes are stable.
