### ISSUE TITLE
Creating a Reporting Module outputs Error

### ISSUE THREAD

**Issue by blaquee** [brad-accuvant/cuckoo-modified#110]
I wasn't sure where to ask this, but since I do use this fork of cuckoo thought I'd try here. I've written my own reporting module that simply omits the behavioral analysis from the results, but Im getting an error

`TypeError: ObjectId('55a7eb34e75a460c391c80de') is not JSON serializable`

The modified code only does this:

``` python
        output = dict()
        report = dict(results)
        output.update( (key,value) for (key,value) in report.items() if key is not "behavior")
```

I've also tried this variant

``` python

new = { key: value for key,value in results.items() if key is not "behavior" }
```

Is the mongoID in the results somewhere? I can't seem to track down what type of object result is, I assumed it was a dictionary.

regards,

**Comment by blaquee** [comment]
The error occurs during processing btw.

**Comment by brad-sp** [comment]
Are you using the latest version?  Does your version contain this commit? https://github.com/brad-accuvant/cuckoo-modified/commit/70e1e7eafb288c49a5ee16ef4de14caefb9f4556  There shouldn't be anything related to ObjectId in your results since we force Mongo's modifications to occur as the "last" reporting module.

**Comment by blaquee** [comment]
That was it. Thanks man.
