### ISSUE TITLE
INQUIRY: Demux

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#128]
scenario: After merging the latest revision. When submitting compressed file (zip), cuckoo always demux the sample before adding it to the db.

Question: How can we relate the demux file came from a particular zip file?

**Comment by supahal** [comment]
cancel this inquiry hahaha :dart:

**Comment by brad-sp** [comment]
There's no way to do that currently due to the design of Cuckoo.  If you want the ZIP to be extracted in the guest and all the static analysis to be run on the ZIP itself, then choose the "ZIP" package.  That will give you the old behavior.  The new behavior is for sane handling of being able to upload password-protected ZIP files containing individual or collections of samples.
