### ISSUE TITLE
Tor support

### ISSUE THREAD

**Issue by jcannell** [brad-accuvant/cuckoo-modified#139]
"Per-analysis Tor support"

How do you enable this? I see some options in auxilary.conf but those are apparently global (and I don't know how to use it properly, anyway).

Any documentation on this?

**Comment by seanthegeek** [comment]
I ran into the same problem, so I **just** created some scripts to get this working. They work great for me. Let me know how they work for you please!

https://github.com/seanthegeek/routetor

**Comment by brad-sp** [comment]
Nice design actually, much cleaner than what I used locally.  If you can send me a PR that updates the documentation to link to your work, I'll definitely include it.  I'm not sure where it makes most sense in the documentation to place it.

**Comment by seanthegeek** [comment]
Thank you. Done.

**Comment by brad-sp** [comment]
Thanks, looks good.  One question though: have you taken a look at your PCAPs since using Tor?  Do you see both sides of the conversation with the correct IP addresses and ports?  Since the PREROUTING chain happens before packet captures dump the packets, I think you might find some problems there (or at least I did).

**Comment by seanthegeek** [comment]
Yes. The source and destination are correct. I also had similar problems. The key is to bind TOR to the same address as the interface that is being dumped. I tried different configurations from the TOR wiki until I found one that worked.

I use inetsim in a similar way. It also is bound to that interface, and a PREROUTING rule is added at boot, adapted from https://techanarchy.net/2013/10/inetsim-and-ip-addresses/ (The mentioned windows route is not needed).

```
iptables -t nat -A PREROUTING -i vboxnet0 -j REDIRECT
```

The result is that any public IP is routed to inetsim, in case malware does not make use of DNS. Because my scripts use `-I` to insert the rules, any TOR PREROUTING rules take priority over the above rule. By default, my sandbox routes to inetsim, unless TOR is requested.

**Comment by brad-sp** [comment]
I've done that, but still if I look at the TCP connections for instance, all the initial requests are recorded as being to the port 9040 on the interface Tor listens on.  I'm testing following your instructions -- is there something I missed?

**Comment by seanthegeek** [comment]
Strange. Are you using virtualbox? Maybe there's a difference when using KVM or others?

**Comment by brad-sp** [comment]
I'm using KVM here.  Could you send me a PCAP of accessing google.com or something else benign through the Tor-routed VM?  It shouldn't be a Virtualbox/KVM issue, it's a matter of at what point tcpdump is able to see the packets.  brad.spengler@optiv.com

**Comment by seanthegeek** [comment]
Did you get the PCAP?

**Comment by brad-sp** [comment]
Yes, thank you.  It indeed looks perfect.  I'll look into whether the vnet0 interface KVM spawns contains the unmangled packets, and then if so try to figure out a way we can sniff on it given that it doesn't exist prior to the VM being started (and we'll also need to fix the name of it instead of allowing it to autogenerate).

**Comment by brad-sp** [comment]
Just fixed the KVM issue -- the vnet\* interfaces had the unmangled packets we wanted, but they're created at runtime and with auto-generated names by default, so I wrote up the documentation and a script that gets it working the same as with VirtualBox.

Thanks again!

**Comment by seanthegeek** [comment]
@brad-accuvant Can you share your docs? I'm I'm migrating over to KVM, and I can't figure out how to set the vnet\* IDs manually.

**Comment by KillerInstinct** [comment]
It was merged with this commit: https://github.com/brad-accuvant/cuckoo-modified/commit/963530d57f35dc2a1b6b6b146c7cf860f321bdc9

**Comment by seanthegeek** [comment]
Thanks. Not sure how I missed that.
