### ISSUE TITLE
MongoDB Screenshots not able to save/purge them

### ISSUE THREAD

**Issue by Toklandarr** [brad-accuvant/cuckoo-modified#146]
in modules/reporting/mongodb.py: 286

```
child_key, csize = self.debug_dict_size(report[parent_key])[0]
```

When having a lot of screenshots ( i had 102 for some reason) this code will not be able to delete the data to fit into mongodb. 
parent_key will equal "screenshots" and report[parent_key] is a list() and not a dict() so this yields an AttributeError since debug_dict_size expects a dict...

**Comment by KillerInstinct** [comment]
Do you have a traceback? I am unable to replicate this. Generated 200 screenshots.

I don't think the root cause of this is due to 'X' amount of screenshots. Each screenshot is saved into MongoDB per a for loop, that is, we retrieve one ObjectID per screenshot. So unless you have a screenshot that's over 16MB, or millions of list entries (causing the json to have a large size of text) the screenshots should never trigger the size issue.

**Comment by defekkt** [comment]
I had the same issue, fixed by "unifying" screenshot dict naming and happens only when html reports are enabled.

**Comment by defekkt** [comment]
see
https://github.com/brad-accuvant/cuckoo-modified/pull/147

**Comment by brad-sp** [comment]
Toklandarr: does the above fix resolve your issue as well?  It's included in the latest version.

Thanks,
-Brad
