### ISSUE TITLE
Probem with malheur

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#203]
I activated malheur in the latest version and got this traceback :
malheur: invalid option -- 'c'
malheur: invalid option -- 'c'
Usage: malheur [options] <action> <dataset>
Actions:
  distance       Compute distance matrix for malware reports
  prototype      Extract prototypes from malware reports
  protodist      Compute distance matrix for prototypes
  cluster        Cluster malware reports into similar groups
  classify       Classify malware reports using labeled prototypes
  increment      Incremental analysis of malware reports
  info           Print information about internal state of Malheur
Options:
  -m <maldir>    Set malheur directory. [/usr/local/var/malheur]
  -o <outfile>   Set output file for analysis. [malheur.out]
  -d <dumpfile>  Dump feature vectors to file in libsvm format.
  -r             Reset internal state of Malheur.
  -n             Don't save internal state of Malher.
  -v             Increase verbosity.
  -V             Print version and copyright.
  -h             Print this help screen.
See manual page malheur(1) for more information.

Can this to be solved ?

Thanks

**Comment by brad-sp** [comment]
Yes, you'll need to update to the latest version of malheur from their git repo.  I updated it since due to the bug in the original malheur tarball that will cause a crash when run against a single report, everyone will likely be downloading malheur for the first time by cloning the current state of the malheur repo.
