### ISSUE TITLE
No extracting strings

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#49]
I am running a file adn when I use the strings command in terminal mode I see the strings.
Running it within cuckoo doesn't provide any strings.

file can be found at https://www.virustotal.com/en/file/140edc041bc2a38e94c95260de9e2df59202daa175a33fb2f045e5b7c0d8e87b/analysis/

What seems to be the problem and can this be solved ?

Thanks

**Comment by brad-sp** [comment]
It's because that file is vbscript -- there aren't any "strings" in it, the entire file is itself one big "string" modulo a nul terminator.  Since there's no nul terminator, by default our strings processing won't bother with it.  Unlike upstream, by default we don't display strings without null terminators, as on many samples this simply generates 90% useless results.  If you want the upstream behavior instead, then set nullterminated_only to "no" in conf/processing.conf under the "strings" heading.
